export const GET_CRASH_DETAILS_REQUEST = "GET_CRASH_DETAILS_REQUEST"; 
export const GET_CRASH_DETAILS_SUCCESS = "GET_CRASH_DETAILS_SUCCESS"; 
export const GET_CRASH_DETAILS_FAILURE = "GET_CRASH_DETAILS_FAILURE"; 

export const GET_SINGLECRASH_DETAILS_REQUEST = "GET_CRASHSINGLE_DETAILS_REQUEST"; 
export const GET_SINGLECRASH_DETAILS_SUCCESS = "GET_CRASHSINGLE_DETAILS_SUCCESS"; 
export const GET_SINGLECRASH_DETAILS_FAILURE = "GET_CRASHSINGLE_DETAILS_FAILURE"; 